### ISSUE TITLE
Says I am offline, but this post proves that I am not :)

### ISSUE THREAD

**Issue by bitboxer** [bascht/binichonline#1]
I just tried to use this, but sadly I see this on my mac:

![bildschirmfoto 2015-09-15 um 15 47 31](https://cloud.githubusercontent.com/assets/56195/9878065/179a2e1c-5bc1-11e5-9a9a-b839c7f7d314.png)

Is there anything I can do to help you debug this?

**Comment by bascht** [comment]
:blush: Thanks for reporting this. As @moonglum already noticed: I'm still using my bahn-debugging code and testing against `localhost:8000` (which is just `python -m SimpleHTTPServer`). So – feel free to add any other host in `src/lib.rs`. Nice Fira by the way. :)

**Comment by bitboxer** [comment]
thanks for fixing :wink:
